### ISSUE TITLE
Current Tasks

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#14]
Release:
- [x] Create PC and Mac exectuables. ( @maxwey )
- [x] Put up itch.io page and download link. ( @taagestorey )

**Comment by ianbattin** [comment]
Added the first go at the debris "enemy".
Still have to work on the collision a bit and make sure the image rotates correctly.
Not sure if I like it, it's too sporadic and makes it so theres too much going on in the screen

**Comment by taagestorey** [comment]
List updated. Please try to complete all current tasks (other than music) by this coming Thursday the 18th.

We're planning to meet at 8:30pm via Skype on Thursday night. Please comment here if you're unable to attend, thanks!

@maxwey @ianbattin @OrangePorridge @ra1nyday

**Comment by taagestorey** [comment]
- Max still looking at top of level.
- Stuka cockpit will be taken out.
- Falling through diagonal platforms.
- The player can currently fall when switching to shooting animation.
- Size change of game causes distortion to collision systems.

**Comment by taagestorey** [comment]
Stuka fight changes: ( @maxwey @ianbattin )

- Can we temporarily disable text intro and pre-level dialogue?

- Walking paratroopers in the boss fight are jumping when the player double jumps and also fall off if he falls. Let's change so that they don't move at the same time.

- Shooting sound-effect continues after the Stuka leaves the screen. Let's have the sound stop after it exits the screen.

- Instead of having paratroopers coming out of the Stuka let's have them drop from the top of the screen.

- Can we have the small fires timed to go out/disappear after 5 seconds each?

- Please change the double jump text show up right after the Stuka shows up, hovers and leaves.

**Comment by taagestorey** [comment]
**Ending Animation:**

After the Stuka falls away the cockpit of the B-17 opens and everything goes into slow motion. Henry faces left (toward the cockpit). Parachute pack rises out of cockpit with straps flapping. Henry runs (use running sprites at bottom of sheet) to the left and at a certain point jumps toward the pack. Screen fades to white.

**Comment by taagestorey** [comment]
![y](https://cloud.githubusercontent.com/assets/15072168/15495355/23119c5a-2144-11e6-954d-2786bb4c3ee8.jpg)
